import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

import {
  DynamicContextProvider,
  DynamicWagmiConnector,
  EthereumWalletConnectors,
} from '../lib/dynamic';
import NavBar from '@/components/NavBar';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'gmReady',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.3.0/flowbite.min.css"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <DynamicContextProvider
          settings={{
            environmentId: '2ddebf12-13c3-49c8-ba67-c2ecb3da5edc',
            walletConnectors: [EthereumWalletConnectors],
          }}
        >
          <DynamicWagmiConnector>
            <div>
              <NavBar />
              <div className="mt-10">{children}</div>
            </div>
          </DynamicWagmiConnector>
        </DynamicContextProvider>
      </body>
    </html>
  );
}
